name: Node.js CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        # Changed from ./packages/web to packages/web
        working-directory: packages/web

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install Dependencies
      run: pnpm install --no-frozen-lockfile
      
    - name: Run Project Build
      run: pnpm run --if-present build
